apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: calc-namespace
  labels:
    app: frontend
    project: calc
    division: finance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      project: calc
      division: finance
  template:
    metadata:
      labels:
        app: frontend
        project: calc
        division: finance
    spec:
      containers:
        - name: frontend
          image: muralielavarthi/frontend:2.0.0
          command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"] # override the default command to use our custom nginx.conf
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf # subPath is needed to mount a single file from the ConfigMap.
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config

            #subPath: nginx.conf to replace only the file, not the whole directory.
