apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: calc-namespace
  labels:
    app: backend
    project: calc
    division: finance
data:
  BACKEND_PORT: "8080"
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: calcdb
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
