apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: calc-namespace
  labels:
    app: database
    project: calc
    division: finance
data:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: calcdb
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
