apiVersion: v1
kind: Service
metadata:
  name: headless-service
  namespace: calc-namespace
  labels:
    app: mysql
    project: calc
    division: finance
spec:
  clusterIP: None
  selector:
    app: mysql
    project: calc
    division: finance
